ssehub:
  url: http://sse.vg.no/vglive
  interval: 2
amqp:
  host: ssehub-mq.int.vgnett.no
  port: 5672
  exchange: vg.fanout
  path: vglive

collectors:
  statsd:
    enabled: false
    host: xxx.xxx.xxx.xxx

  prometheus:
    enabled: false
    bind: :2000
